language: objective-c
osx_image: xcode10
branches:
  only:
    - master
    - develop
    - ci
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script: make test
    - name: Integration Tests
      before_install:
        - brew update
        - brew install rename cookiecutter
      script:
        - |
          echo version: \'.branch\(\"$TRAVIS_COMMIT\"\)\' > $TRAVIS_BUILD_DIR/AarKay/AarKayData/NoPlugin/aarkay-plugin-pluginlowername/Package.yml
        - git commit -am "Update Plugin Package.swift"
        - sh scripts/run
        - sh scripts/template
        - cd AarKay && cookiecutter --no-input $TRAVIS_BUILD_DIR && cd ..
        - make build
        - echo "./../../AarKay, r-$TRAVIS_COMMIT" > AarKay/AarKayFile
        - .build/release/AarKayRunner init
        - echo "./aarkay-plugin-personal, b-master" >> AarKay/AarKayFile
        - .build/release/AarKayRunner install
        - .build/release/AarKayRunner --verbose --force
        - .build/release/AarKayRunner init --global
        - echo "https://github.com/RahulKatariya/AarKay.git, r-$TRAVIS_COMMIT" > $HOME/AarKay/AarKayFile
        - .build/release/AarKayRunner update --global
        - cd aarkay-plugin-pluginlowername && ../.build/release/AarKayRunner -vfg
        - sh scripts/run
