os: osx
language: objective-c
osx_image: xcode10.2
branches:
  only:
    - master
    - develop
    - ci
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

aliases:
  - &xcode
    script:
      - swift package generate-xcodeproj --enable-code-coverage
      - xcodebuild -scheme AarKay-Package test
    env:
      - JOB=XCODE
  - &swiftpm
    script:
      - swift --version
      - make build
      - make test
    git:
      submodules: false
  - &swiftpm_darwin
    <<: *swiftpm
    env: JOB=SWIFTPM_DARWIN
  - &swiftpm_linux
    <<: *swiftpm
    sudo: required
    dist: trusty
    os: linux
    language: generic
    before_install:
      - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    env: JOB=SWIFTPM

matrix:
  include:
    - <<: *xcode
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'AarKay' -J 'AarKayKit' -J 'AarKayRunnerKit' -J 'aarkay-plugin-aarkay' -J 'SharedKit'
    - <<: *swiftpm_darwin
    - <<: *swiftpm_linux
    - stage: Integration
      before_install:
        - brew update
        - brew install rename cookiecutter
      script:
        - |
          echo version: \'.revision\(\"$TRAVIS_COMMIT\"\)\' > $TRAVIS_BUILD_DIR/AarKay/AarKayData/NoPlugin/aarkay-plugin-pluginlowername/Package.yml
        - |
          echo version: \'r-$TRAVIS_COMMIT\' > $TRAVIS_BUILD_DIR/AarKay/AarKayData/NoPlugin/Sources/AarKayRunnerKit/RunnerFiles/AarKayDependency.Runner.yml
        - git commit -am "Update Plugin Package.swift"
        - sh scripts/run
        - sh scripts/template
        - cd AarKay && cookiecutter --no-input $TRAVIS_BUILD_DIR name=test && cd ..
        - make build
        - echo "./../../AarKay, r-$TRAVIS_COMMIT" > AarKay/AarKayFile
        # - echo "https://github.com/rahulkatariya/aarkay-plugin-personal.git, b-master" >> AarKay/AarKayFile
        - .build/release/AarKayRunner init
        - echo "./aarkay-plugin-test, b-master" >> AarKay/AarKayFile
        - .build/release/AarKayRunner install
        - .build/release/AarKayRunner --verbose --force #--exitOnError
        - .build/release/AarKayRunner init --global
        - echo "https://github.com/RahulKatariya/AarKay.git, r-$TRAVIS_COMMIT" > $HOME/AarKay/AarKayFile
        - .build/release/AarKayRunner update --global
        - cd aarkay-plugin-pluginlowername && ../.build/release/AarKayRunner -vfg
        - sh scripts/run
