#!/bin/bash

set -e
echo "version: '.upToNextMinor(from: \"$1\")'" > AarKay/AarKayData/NoPlugin/aarkay-plugin-PLUGINLOWERNAME/Package.yml
echo "public let AarKayVersion = \"$1\"" > Sources/AarKayRunnerKit/AarKayVersion.swift
git commit -am "Release v$1 🚀"
sh scripts/run
sh scripts/template
git commit -a --amend --no-edit
git tag v$1
git push origin --tags
